name: Generate Feed
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Podcast Generator SZ
        uses: semionza/sz-podcast-generator-test@main
      
          
